Pepepedia2/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basic_app/urls.py
from django.conf.urls import url
from django.urls import include, path
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'basic_app'
urlpatterns = [

    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('post/createpost/', views.AddPostView.as_view(), name='createpost'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('user/<int:pk>/', views.UserAnnouncesList.as_view(), name='author_view'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)


    def __str__(self):
        return self.user.username

class Post(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='image_files', blank=True)

    def __str__(self):
        return self.author

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo, Post

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site',)

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'image')

basic_app/views.py
from django.shortcuts import render, redirect
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
from django.views.generic import (View, TemplateView, ListView, DetailView)
from basic_app.forms import PostForm
from basic_app.models import Post
# Create your views here.

class IndexView(ListView):
    template_name = 'basic_app/index.html'
    model = Post
    

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html', {'user_form':user_form,'prifile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!')

        else:
            print('Someone tried to login and failed')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse('Invalid login details supplied!')

    else:
        return render(request,'basic_app/login.html', {})

class PostDetailView(DetailView):
    context_object_name = 'detail_post'
    template_name = 'basic_app/post_detail.html'
    model = Post


class AddPostView(TemplateView):
    template_name = 'basic_app/createpost.html'

    def get(self, request):
        form = PostForm()
        posts = Post.objects.all()
        args = {'form':form, 'posts':posts}
        return render(request, self.template_name, args)

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.title = form.cleaned_data['title']
            if 'image' in request.FILES:
                post.image = request.FILES['image']
            post.save()
            return redirect('index')
        args = {'form':form, 'image':image}
        return render(request,self.template_name,args)


class UserAnnouncesList(ListView):
    model = Post
    template_name = 'basic_app/author_view.html'
    context_object_name = 'author_posts'

    def get_queryset(self):
        return Post.objects.filter(author=self.kwargs['pk'])

templates/basic_app/author_view.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>{{ author_view.author }}</h1>
        {% for post in author_posts %}
             <h2>
            <a href="{% url 'basic_app:detail_post' post.pk %}" title="Tytuł" role="link" class="Title">{{ post.title }}</a>
        </h2>
        <span>{{ post.author }}</span>
        <img src="{% if post.image %}{{ post.image.url }}{% else %}{{ '#' }}{% endif %}" width="20"/>
        {% endfor %}
    </div>
{% endblock %}

templates/basic_app/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
    <head>
        <meta charset='utf-8'>
        <title></title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
       <nav class = 'navbar navbar-default navbar-static-top'>
        <div class = 'container'>
            <ul class='nav navbar-nav'>
                <li><a class='navbar-brand' href="{% url 'index' %}">Django</a></li>
                <li><a class='navbar-brand' href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class='navbar-brand' href="{% url 'basic_app:createpost' %}">Create</a></li>
                <li><a class='navbar-brand' href="{% url 'basic_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>

                {% else %}
                <li><a class='navbar-link' href="{% url 'basic_app:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
       </nav>
       <div class="container">
        {% block body_block %}
        {% endblock body_block %}
       </div>
    </body>
</html>

templates/basic_app/createpost.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="" value="Posted">
        </form>
    </div>
{% endblock %}

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Pepedia!</h1>
    {% for post in post_list %}
        <h2>
            <a href="{% url 'basic_app:detail_post' post.pk %}" title="Tytuł" role="link" class="Title">{{ post.title }}</a>
        </h2>
        <span>
            <a href="{% url 'basic_app:author_view' post.author_id %}" title="Autor" role="link" class="Author">{{ post.author }}</a>
        </span>
        <img src="{% if post.image %}{{ post.image.url }}{% else %}{{ '#' }}{% endif %}" width="20"/>
    {% endfor %}
</div>
{% endblock body_block %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
    </form
</div>

{% endblock body_block %}

templates/basic_app/post_detail.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h2>
            <a href="{{ detail_post.pk }}" title="Tytuł" role="link" class="Title">{{ detail_post.title }}</a>
        </h2>
        <span>Author: {{ detail_post.author }}</span>
        <img src="{% if detail_post.image %}{{ detail_post.image.url }}{% else %}{{ '#' }}{% endif %}" />
    </div>
{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here:</h1>
            <h3>Fill out the form:</h3>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
                
        {% endif %}
    </div>

{% endblock body_block %}